#define BUFLENGTH 100


/* prototype parser functions (generated by lemon.c) */
void *ParseAlloc(void *(*mallocProc)(size_t));
void ParseFree(
  void *p,                    /* The parser to be deleted */
  void (*freeProc)(void*)     /* Function used to reclaim memory */
  );
void Parse(
  void *yyp,                   /* The parser */
  int yymajor,                 /* The major token code number */
  int yyminor       /* The value for the token */
  );


typedef struct cStruct
{
  char cmd[BUFLENGTH];
  int cmd_len;
  int spuAddr;
} cmdStruct;

void accumCmd(cmdStruct * c, int token, int start);
void dispatchMCUCmd(int spuAddr, cmdStruct * c);
void dispatchLEDCmd(int spuAddr, cmdStruct * c);
void dispatchSPUCmd(int spuAddr, cmdStruct * c);
void accumAddrDigit(int x);
void resetAddress(void); 
void doScanner(void * pParser(), int inChar);






