#ifndef SCANNER_H_
#define SCANNER_H_

#define BUFLENGTH 256
/*flags for command-line debug options to dispatcher.c */ 
/*Dillo Added 9/25/07 				       */
#define DEBUG_GPS 0x01
#define DEBUG_IMU 0x02
#define DEBUG_LED 0x04
#define DEBUG_MCU 0x08
#define DEBUG_SPU 0x10
#define DEBUG_T   0x20 


/* prototype parser functions (generated by lemon.c) */
void *ParseAlloc(void *(*mallocProc)(size_t));
void ParseFree(
  void *p,                    /* The parser to be deleted */
  void (*freeProc)(void*)     /* Function used to reclaim memory */
  );
void Parse(
  void *yyp,                   /* The parser */
  int yymajor,                 /* The major token code number */
  int yyminor       /* The value for the token */
  );


typedef struct cStruct
{
  char cmd[BUFLENGTH];
  int cmd_len;
  int spuAddr;
} cmdStruct;


void accumCmd(cmdStruct * c, int token, int start);
void dispatchMCUCmd(int spuAddr, cmdStruct * c);
void dispatchLEDCmd(int spuAddr, cmdStruct * c);
void dispatchSPUCmd(int spuAddr, cmdStruct * c);
void dispatchGpggaMsg(cmdStruct * c);
void dispatchGpvtgMsg(cmdStruct * c);
void accumAddrDigit(int x);
void resetAddress(void); 
void doScanner(void * pParser(), char* str);

enum EDebugArea{
  eNoLog =0,
  eDefaultLog,
  eDispatcherLog,
  eLedLog,
  eSpuLog,
  eMcuLog,
  eGpsLog
};

enum EDebugLevel{
  eLogDebug =0,
  eLogInfo,
  eLogWarn,
  eLogError
};

void logit(int nLogArea, int nLogLevel,  
	 char* strFormattedSring, ...);

int isLogging(int nLogArea, int nLogLevel);


#endif /*SCANNER_H_*/
